#!/bin/bash

file_path="secret.txt"

echo "Hello $REMOTE_ADDR:$REMOTE_PORT,"
echo

if [ "$REQUEST_METHOD" == "GET" ]; then
  if [ -e "$file_path" ]; then
    echo "Your secret is \"$(cat $file_path)\", please keep it safe."
  else
    echo "You don't have a secret yet, please set one first."
  fi
elif [ "$REQUEST_METHOD" == "POST" ]; then
  if [ -e "$file_path" ]; then
    echo "You already have a secret, please keep it safe."
  else
    if [ $# -gt 0 ]; then
      echo "$@" > $file_path
      echo "Your secret has been set."
    else
      echo "You must pass in a valid phrase to set as your secret."
    fi
  fi
elif [ "$REQUEST_METHOD" == "DELETE" ]; then
  if [ -e "$file_path" ]; then
    rm $file_path
    echo "Your secret has been deleted."
  else
    echo "You don't have a secret yet, please set one first."
  fi
else
  echo "You are not allowed to access this page."
fi

echo
echo "Sincerely, $SERVER_NAME"
